### ISSUE TITLE
Noob questions to be sure 😖

### ISSUE THREAD

**Issue by pingwinekZ** [TheFormidable/Unbrick#1]
1. Is it safe to update hyperos with this installed?
2. Is it needed to flash this again after hyperos update?
3. Can there be any problems between this and KernelSU or magisk?

**Comment by TheFormidable** [comment]
A) Updating hyperOS with the Eng preloader already installed will overwrite it to Normal hyperOS preloader, So you should reinstall it if you want to continue making modifications in a "safe" way. There is no risk in updating hyperOS officially.

B) In what I've tested, neither ksu nor magisk have any major difficulties when using it.
