### ISSUE TITLE
This is just a question

### ISSUE THREAD

**Issue by 4niss-1** [TheFormidable/Unbrick#2]
Do i have to flash before bricking? or after?
and do have to do it on an entirely new phone? (im getting a poco x6 pro on my birthday and  i dont like hyperos)
i do infact want to install a custom rom when its available (i like android aosp's)
will this make sure my device isnt screwed when i brick it?

**Comment by TheFormidable** [comment]
1)you must install it first, before reaching the hard brick where it is not possible to install the preloader
2)To install it you must logically have the bootloader unlocked so a "new" device must have a few days of use
3) is it compatible with aosp (lineage OS tested)
4)I haven't seen yet cases of hardbricking on devices that already use the eng preloader, so it's not 100% certain it will work, but in the case of a hardbrick happening it "should" help.
